[FIX] connector_carepoint: Sync issues
LasLabs/odoo-connector-carepoint pull request #28
Opened 2016-10-21 22:42 UTC by lasley

[FIX] connector_carepoint: Sync issues  …
* Fix dates on prescription and prescription line export
* Fix date on prescription import
* Fix address and phone syncing
* Add missing binders
* Add missing consumers
* Handle blank zips on import/export
* Account for +1 variance on Carepoint Refills Left
* Support multiple types of phone numbers
* Upgrade for support w/ Python-Carepoint v.0.1.5

2016-10-27 17:23 UTC, lasley commented
Ready for review assuming CI 🍏 

I'll squash into a meaningful commit after. Was getting tired of editing the bullet points as issues rolled in

2016-10-28 02:22 UTC, tedsalmon requested changes
Minor issue with the test, otherwise LGTM

2016-10-28 02:22 UTC, t3ddftw commented on connector_carepoint/tests/models/test_phone_abstract.py
> +    def test_get_by_partner_create(self):
Duplicate method name. Also declared on line 136

2016-10-28 06:26 UTC, tedsalmon approved these changes

2016-10-28 06:27 UTC, t3ddftw commented
I believe you want to squash these commits, so I'll leave this unmerged :)

2016-10-28 15:06 UTC, merged